window.REHAB_DATA = [
    {
        "id":  "1",
        "district":  "중구",
        "name":  "의료법인 동강의료재단 동강병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 뇌손상, 척수손상, 근골격계 수술 후 재활, 보행·연하·통증 관리",
        "specialty":  "종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "울산광역시 중구 태화로 239",
        "phone":  "052-241-1114",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ3OSQ0NjE0ODEjODEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "재활의학과 1명 검색 확인. 산재/자동차보험은 전화 확인 권장"
    },
    {
        "id":  "2",
        "district":  "중구",
        "name":  "의료법인 청남의료재단 세민에스요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/산재 재활인증",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "뇌졸중 후유증, 중추신경계 재활, 장기요양 환자, 물리/작업치료, 전문재활치료 후보",
        "specialty":  "산재 재활인증의료기관",
        "recovery":  "해당없음",
        "workersComp":  "재활인증 확인",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 중구 내황4길 11",
        "phone":  "052-293-2000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQxIyQwMyQzNjEyMjIjNDEjJDEjJDgjJDgz / https://www.comwel.or.kr/comwel/comp/trmt/rein02.jsp",
        "verification":  "HIRA/공단 확인",
        "notes":  "근로복지공단 재활인증의료기관 현황에 울산 중구 기관으로 확인"
    },
    {
        "id":  "3",
        "district":  "중구",
        "name":  "의료법인 우아의료재단 길메리요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료/양한방협진 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 뇌졸중 후유증, 장기요양, 물리치료, 양한방협진 후보",
        "specialty":  "요양병원 재활치료 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 중구 서원1길 106",
        "phone":  "052-296-0030",
        "sources":  "https://ddoga.co.kr/ltch/13/JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzExIyQxIyQ3IyQxMyQyNjE4MzIjNzEjJDEjJDgjJDgz/W01",
        "verification":  "후보/전화확인",
        "notes":  "HIRA 직접 상세 재검색 필요. 공개 요양시설 정보상 재활치료/물리치료 표기"
    },
    {
        "id":  "4",
        "district":  "중구",
        "name":  "효성요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 장기요양, 물리치료 후보",
        "specialty":  "요양병원 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울사광역시 중규 학산로 5 (학산동)",
        "phone":  "052-288-6100",
        "sources":  "https://www.peonani.com/facility/1459/%ED%9A%A8%EC%84%B1%EC%9A%94%EC%96%91%EB%B3%91%EC%9B%90",
        "verification":  "후보/전화확인",
        "notes":  "HIRA에서 중구 요양병원으로 재검색하여 재활의학과/물리치료실 여부 확인 필요"
    },
    {
        "id":  "5",
        "district":  "남구",
        "name":  "울산병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 뇌손상, 척수손상, 근골격계 수술 후 재활, 보행장애, 통증재활",
        "specialty":  "종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "울산광역시 남구 월평로171번길 13",
        "phone":  "052-259-5000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQyIyQzIyQwMCQyNjEyMjIjNDEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 1명 확인"
    },
    {
        "id":  "6",
        "district":  "남구",
        "name":  "울산연세병원",
        "type":  "병원",
        "inclusion":  "재활의학과 보유 병원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래/입원 재활 가능성",
        "conditions":  "근골격계 수술 후 재활, 통증, 보행장애, 물리치료",
        "specialty":  "재활의학과/정형·통증 연계",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울사광역시 남규 대학로 152 (무거동)",
        "phone":  "052-700-2580",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzMxIyQxIyQ3IyQ4OSQ0NjEwMDIjNjEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 1명 검색 확인. 주소/전화 상세 재확인 필요"
    },
    {
        "id":  "7",
        "district":  "남구",
        "name":  "울산365재활의학과병원",
        "type":  "병원",
        "inclusion":  "재활의학과 전문 병원급",
        "rehabDept":  "있음",
        "specialists":  "2명(HIRA)",
        "careType":  "입원재활/외래재활",
        "conditions":  "뇌졸중·척수손상·근골격계·수술 후 재활, 물리·작업치료, 간호간병통합서비스",
        "specialty":  "재활의학과 병원 / 간호간병통합서비스",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 번영로 195, 2층·3층 일부",
        "phone":  "052-700-5200",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzMxIyQxIyQ3IyQ4OSQzNjE4MzIjNDEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 2명, 물리치료사/작업치료사 인력 확인"
    },
    {
        "id":  "8",
        "district":  "남구",
        "name":  "한양연합재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 외래",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 도수/물리치료, 수술 후 재활, 교통사고 후유증 후보",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 남구 삼산로 243, 3층",
        "phone":  "052-265-5824",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkNDgxOTYxIzExIyQxIyQzIyQ4OSQzNjEyMjIjNjEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "기관명·주소·전화 확인. 전문의 수는 HIRA 상세 재확인 필요"
    },
    {
        "id":  "9",
        "district":  "남구",
        "name":  "바른몸재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 외래",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 스포츠손상, 도수/물리치료, 수술 후 재활, 보행·자세교정",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 남구 울밀로 2906, 한솔애플타워 6~7층",
        "phone":  "052-225-8875",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkNDgxMzUxIzQxIyQxIyQ3IyQ5OSQyNjEyMjIjODEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 1명, 물리치료사 6명 검색 확인"
    },
    {
        "id":  "10",
        "district":  "남구",
        "name":  "서울척재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 외래",
        "rehabDept":  "있음",
        "specialists":  "2명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "척추·관절 통증, 도수/물리치료, 수술 후 재활, 보행·근력저하",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 남구 대학로131번길 4, 울산대 유파티오 131 3층",
        "phone":  "052-224-8885",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkNDgxOTYxIzMxIyQxIyQzIyQ3OSQyNjE4MzIjNjEjJDEjJDQjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 2명, 물리치료사/작업치료사 확인"
    },
    {
        "id":  "11",
        "district":  "남구",
        "name":  "의)우아의료재단 달동길메리요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/재활의학과 보유",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "입원재활/요양재활",
        "conditions":  "뇌졸중 후유증, 장기요양, 신경외과/재활의학과 협진, 물리치료",
        "specialty":  "보훈위탁진료요양기관",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 돋질로 146",
        "phone":  "052-996-0030",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ2MiQyNjE0ODEjODEjJDEjJDYjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 1명, 물리치료 실시기관 확인"
    },
    {
        "id":  "12",
        "district":  "남구",
        "name":  "의료법인 청산의료재단 효원요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료 후보",
        "rehabDept":  "없음(HIRA 0명)",
        "specialists":  "0명(HIRA)",
        "careType":  "입원재활/요양재활 후보",
        "conditions":  "노인성 질환, 장기요양, 물리치료실 운영, 재활의학과 전문의는 HIRA상 0명",
        "specialty":  "요양병원 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 봉월로 155",
        "phone":  "052-950-7500",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQxIyQ4MiQ0NjE0ODEjNTEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA상 재활의학과 0명이나 물리치료실 6실 확인. 재활중점 여부 전화 확인"
    },
    {
        "id":  "13",
        "district":  "남구",
        "name":  "따사랑요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활 후보",
        "conditions":  "노인성 질환, 장기요양, 물리치료/재활치료 후보",
        "specialty":  "요양병원 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 봉월로 161",
        "phone":  "052-261-5567",
        "sources":  "https://urc.uuh.ulsan.kr/urc/index.php?CgCode=NM\u0026pCode=memclinic\u0026pg=6",
        "verification":  "후보/전화확인",
        "notes":  "울산대병원 협력병원 목록 기반. HIRA 상세 재검색 필요"
    },
    {
        "id":  "14",
        "district":  "남구",
        "name":  "울산자생한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/척추·관절 한방병원",
        "rehabDept":  "해당없음",
        "specialists":  "한방재활의학과 3명(HIRA)",
        "careType":  "외래/입원 한방재활",
        "conditions":  "척추·관절질환, 추나요법, 교통사고 후유증, 한방재활, 의·한 협진",
        "specialty":  "한방재활의학과 / 의·한협진 시범",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 삼산로 51",
        "phone":  "1577-0007",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?isNewWindow=Y\u0026ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkMTMkMzgxMTkxIzExIyQyIyQzIyQwMCQzNjEwMDIjNTEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "한방재활의학과 3명 검색 확인"
    },
    {
        "id":  "15",
        "district":  "동구",
        "name":  "학교법인 울산공업학원 울산대학교병원",
        "type":  "상급종합병원",
        "inclusion":  "재활의학과 보유 대학병원",
        "rehabDept":  "있음",
        "specialists":  "3명(HIRA)",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중, 뇌손상, 척수손상, 파킨슨병, 보행장애, 연하·인지·언어재활, 소아/암재활 후보",
        "specialty":  "대학병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재 지정/재활인증 여부 별도 확인",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "울산광역시 동구 대학병원로 25",
        "phone":  "052-250-7000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ5OSQyNjE4MzIjNDEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 3명 확인"
    },
    {
        "id":  "16",
        "district":  "동구",
        "name":  "엄재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 외래",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 보행·근력저하, 수술 후 재활, 물리·작업치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 동구 대학길 43, 4층",
        "phone":  "052-234-7575",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkNDgxOTYxIzIxIyQyIyQ1IyQwMCQyNjEwMDIjODEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 재활의학과 1명, 물리치료사 4명/작업치료사 2명 확인"
    },
    {
        "id":  "17",
        "district":  "동구",
        "name":  "큰나무정형외과의원",
        "type":  "의원",
        "inclusion":  "근골격계 재활/통증 외래 후보",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "외래 중심",
        "conditions":  "척추·관절 통증, 수술 후 재활, 물리치료 후보",
        "specialty":  "정형/재활 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 동구 방어진순환도로 711",
        "phone":  "052-232-8880",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMiMkNCMkMDAkMzgxMTkxIzExIyQxIyQzIyQ5MiQzNjEyMjIjNTEjJDEjJDIjJDgz",
        "verification":  "후보/전화확인",
        "notes":  "재활의학과 전문의 여부는 확인필요. 근골격계 재활 후보로만 분류"
    },
    {
        "id":  "18",
        "district":  "북구",
        "name":  "북울산병원",
        "type":  "병원",
        "inclusion":  "회복기 재활의료기관/재활의학과 보유",
        "rehabDept":  "있음",
        "specialists":  "4명(HIRA)",
        "careType":  "회복기/입원재활/재택의료",
        "conditions":  "뇌졸중, 뇌손상, 척수손상, 보행장애, 일상생활동작, 물리·작업치료, 재택의료",
        "specialty":  "보건복지부 제3기 회복기 재활의료기관 / 재활환자 재택의료 시범",
        "recovery":  "제3기 지정",
        "workersComp":  "재활인증 확인",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 북구 신답로 37",
        "phone":  "052-293-8888",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkMzgxMzUxIzMxIyQxIyQ3IyQ3OSQyNjE0ODEjNjEjJDEjJDQjJDgz / https://www.comwel.or.kr/comwel/comp/trmt/rein02.jsp",
        "verification":  "HIRA/공식/공단 확인",
        "notes":  "HIRA 특수진료가능분야에 회복기 재활의료기관 표시, 재활의학과 4명. 공단 재활인증의료기관에도 확인"
    },
    {
        "id":  "19",
        "district":  "북구",
        "name":  "의료법인 송은의료재단 울산시티e병원",
        "type":  "병원",
        "inclusion":  "재활병원/산재 재활인증",
        "rehabDept":  "있음",
        "specialists":  "확인필요",
        "careType":  "입원재활/외래재활",
        "conditions":  "로봇치료, 중추신경계 재활, 물리·작업치료, 간호간병통합서비스, 산재 재활",
        "specialty":  "산재 재활인증의료기관",
        "recovery":  "해당없음",
        "workersComp":  "재활인증 확인",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 북구 산업로 1001",
        "phone":  "052-280-8000",
        "sources":  "https://www.comwel.or.kr/comwel/comp/trmt/rein02.jsp / https://medieus.com/sub_detail/hospital_detail.asp?hos_num=1326",
        "verification":  "공단/후보 확인",
        "notes":  "공단 재활인증 목록에 울산시티e병원 확인. HIRA 상세 재검색 필요"
    },
    {
        "id":  "20",
        "district":  "북구",
        "name":  "의료법인 송은의료재단 울산시티병원",
        "type":  "종합병원",
        "inclusion":  "종합병원/재활연계 후보",
        "rehabDept":  "없음(HIRA 0명)",
        "specialists":  "0명(HIRA)",
        "careType":  "외래/입원 재활 연계 후보",
        "conditions":  "정형·신경계 급성기 후 재활 연계, 울산시티e병원과 구분 필요",
        "specialty":  "종합병원 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 북구 산업로 1007",
        "phone":  "052-280-9000",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkODkkMzgxMzUxIzExIyQxIyQzIyQ3MiQ0NjEwMDIjNTEjJDEjJDIjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA상 재활의학과 0명. 울산시티e병원과 혼동 주의"
    },
    {
        "id":  "21",
        "district":  "울주군",
        "name":  "언양요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료실 보유",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 장기요양, 물리치료실 운영, 재활치료 후보",
        "specialty":  "요양병원 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 울주군 삼남읍 반구대로 785",
        "phone":  "052-262-5200",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ5OSQzNjE4MzIjNDEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 병상/물리치료실 확인. 재활의학과 전문의는 상세 재확인 필요"
    },
    {
        "id":  "22",
        "district":  "울주군",
        "name":  "울산광역시립노인병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/물리치료실 보유",
        "rehabDept":  "확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 치매/장기요양, 물리치료실 운영, 재활치료 후보",
        "specialty":  "공립 요양병원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 울주군 온양읍 덕남로 243",
        "phone":  "052-231-7900",
        "sources":  "https://www.hira.or.kr/ra/hosp/hospInfoAjax.do?ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQ1IyQ4MiQ0NjEwMDIjNzEjJDEjJDgjJDgz",
        "verification":  "HIRA 확인",
        "notes":  "HIRA 물리치료실 9실 검색 확인"
    },
    {
        "id":  "23",
        "district":  "울주군",
        "name":  "이손요양병원",
        "type":  "요양병원",
        "inclusion":  "요양재활/전문재활치료 후보",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "입원재활/요양재활",
        "conditions":  "노인성 질환, 전문재활치료, 물리치료실, 양한방협진 후보",
        "specialty":  "요양병원 재활치료 후보",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 울주군 삼남읍 하방로 39",
        "phone":  "055-780-1000",
        "sources":  "https://eroum.co.kr/search/hospitalDetail?careCenterType=NURSING_HOSPITAL\u0026webYn=Y\u0026ykiho=JDQ4MTYyMiM4MSMkMSMkNCMkOTkkNTgxMzUxIzIxIyQxIyQxIyQ3MiQ0NjEwMDIjNTEjJDEjJDYjJDgz",
        "verification":  "후보/전화확인",
        "notes":  "공개 요양시설 정보상 전문재활치료/물리치료실 표기. HIRA 상세 재검색 필요"
    },
    {
        "id":  "24",
        "district":  "남구",
        "name":  "서울아산린재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 전문의 의원 / 근골격계·신경계 외래 재활",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "목·허리·관절 통증, 뇌졸중 후 통증/재활, 물리/도수치료, 스포츠 재활",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 남구 신정로 39, 3층 (달동)",
        "phone":  "052-268-8999",
        "sources":  "https://www.hira.or.kr",
        "verification":  "HIRA 확인",
        "notes":  "아산병원 출신 재활의학과 전문의 1명 상주."
    },
    {
        "id":  "25",
        "district":  "남구",
        "name":  "아주재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 전문의 의원 / 통증 및 도수치료",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 체형 교정, 도수/물리치료, 스포츠 손상 재활",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 남구 돋질로 369, 3층 (삼산동)",
        "phone":  "052-297-7475",
        "sources":  "https://www.hira.or.kr",
        "verification":  "HIRA 확인",
        "notes":  "삼산동 아주메디컬 건물 위치."
    },
    {
        "id":  "26",
        "district":  "울주군",
        "name":  "울산이손병원",
        "type":  "병원",
        "inclusion":  "전문 재활 병원 / 이손요양병원 연계",
        "rehabDept":  "있음",
        "specialists":  "3명(HIRA)",
        "careType":  "입원재활/외래재활",
        "conditions":  "중추신경계 재활(뇌졸중, 척수손상), 인지/작업치료, 간호간병통합서비스, 수술 후 집중재활",
        "specialty":  "재활치료실 운영 / 간호간병통합서비스",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "울산광역시 울주군 삼남읍 하방로 43",
        "phone":  "055-780-3000",
        "sources":  "http://www.esonhosp.com",
        "verification":  "HIRA 확인",
        "notes":  "요양병원과 분리된 급성기/회복기 재활 병원. 전문의 3명 및 재활 인프라 다수 확인."
    },
    {
        "id":  "27",
        "district":  "남구",
        "name":  "울산 제니스병원",
        "type":  "병원",
        "inclusion":  "소아재활 / 뇌졸중 및 신경재활 병원급",
        "rehabDept":  "있음",
        "specialists":  "2명(HIRA)",
        "careType":  "입원재활/외래재활/소아재활",
        "conditions":  "뇌졸중 후유증, 소아 낮병동 및 재활치료, 로봇재활, 인지/언어재활, 작업치료",
        "specialty":  "소아재활 낮병동 / 로봇재활",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "소아 낮병동 운영",
        "address":  "울산광역시 남구 번영로 160, 제니스병원타석",
        "phone":  "052-274-2009",
        "sources":  "http://www.jenith.co.kr",
        "verification":  "공식 확인",
        "notes":  "소아재활 낮병동을 갖춘 울산 내 아동/성인 통합 재활병원."
    },
    {
        "id":  "28",
        "district":  "남구",
        "name":  "울산중앙병원",
        "type":  "종합병원",
        "inclusion":  "재활의학과 보유 종합병원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "급성기/외래·입원 재활",
        "conditions":  "뇌졸중 후 재활, 근골격계 수술 후 통증/재활, 작업 및 물리치료",
        "specialty":  "종합병원 재활의학과",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "울산광역시 남구 문수로 480 (신정동)",
        "phone":  "052-226-1000",
        "sources":  "https://www.hira.or.kr",
        "verification":  "HIRA 확인",
        "notes":  "신정동 옥동 인근 위치 종합병원."
    },
    {
        "id":  "29",
        "district":  "남구",
        "name":  "에스재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 전문의 의원 / 통증 치료",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "근골격계 통증, 도수치료, 물리치료, 척추·관절 재활",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 남구 수암로 130, 2~3층 (야음동)",
        "phone":  "052-700-5288",
        "sources":  "https://www.hira.or.kr",
        "verification":  "HIRA 확인",
        "notes":  "야음동 대단지 인근 위치."
    },
    {
        "id":  "30",
        "district":  "남구",
        "name":  "강남동강병원",
        "type":  "병원",
        "inclusion":  "재활의학과 보유 병원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래/입원 재활 가능성",
        "conditions":  "뇌졸중 후 재활, 급성기 연계 재활, 근골격계 수술 후 물리치료",
        "specialty":  "재활의학과 보유 병원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "외래/입원 중심",
        "address":  "울산광역시 남구 돋질로 80 (달동)",
        "phone":  "052-241-3114",
        "sources":  "http://kndkmc.or.kr",
        "verification":  "HIRA 확인",
        "notes":  "동강병원 계열 병원."
    },
    {
        "id":  "31",
        "district":  "북구",
        "name":  "뉴욕정형외과재활의학과의원",
        "type":  "의원",
        "inclusion":  "정형외과 및 재활의학과 연계 의원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "디스크, 거북목, 스포츠 재활, 도수치료, 통증 수액",
        "specialty":  "정형/재활 연계 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 북구 호계로 337-10, 2층 (신천동)",
        "phone":  "052-700-7588",
        "sources":  "https://www.hira.or.kr",
        "verification":  "HIRA 확인",
        "notes":  "정형외과 및 재활의학과 각 전문의 상주."
    },
    {
        "id":  "32",
        "district":  "북구",
        "name":  "센텀재활의학과의원",
        "type":  "의원",
        "inclusion":  "재활의학과 전문의 의원",
        "rehabDept":  "있음",
        "specialists":  "1명(HIRA)",
        "careType":  "외래 중심",
        "conditions":  "디스크, 협착증, 만성통증, 물리치료",
        "specialty":  "재활의학과 의원",
        "recovery":  "해당없음",
        "workersComp":  "산재지정 여부 확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "해당없음",
        "address":  "울산광역시 북구 제내1길 2, 필그린상가 302호 (신천동)",
        "phone":  "052-277-2282",
        "sources":  "https://www.hira.or.kr",
        "verification":  "HIRA 확인",
        "notes":  "신천동 필그린상가 3층 위치."
    },
    {
        "id":  "33",
        "district":  "남구",
        "name":  "당당한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/척추·관절 한방병원",
        "rehabDept":  "있음/확인필요",
        "specialists":  "한방재활의학과 1명 이상(확인필요)",
        "careType":  "외래/입원 한방재활",
        "conditions":  "척추·관절질환, 추나요법, 교통사고 후유증, 수술 후 재활, 체형 교정",
        "specialty":  "한방재활의학과 / 양·한방 협진",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 삼산로 247, 마마파파엔베이비빌딩 (달동)",
        "phone":  "052-702-7777",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "한방재활의학과 의료진 상주. 양·한방 협진 및 체형 교정 특화"
    },
    {
        "id":  "34",
        "district":  "남구",
        "name":  "동강한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/양한방협진 한방병원",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활",
        "conditions":  "중풍 후유증, 오십견, 요통, 파킨슨 등 재활 치료",
        "specialty":  "한방재활의학과 / 강남동강병원 협진",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 돋질로 80, (달동)",
        "phone":  "052-241-3114",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "강남동강병원 양·한방 협진 체계. 중풍 및 뇌신경계 재활 치료 중심"
    },
    {
        "id":  "35",
        "district":  "남구",
        "name":  "새봄한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/암재활 한방병원",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활",
        "conditions":  "암 환자 재활, 도수치료, 통합면역 증진, 고주파 온열 치료",
        "specialty":  "암 재활 / 양·한방 협진",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 중앙로 234, (신정동)",
        "phone":  "052-260-9000",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "암 재활 및 도수치료 프로그램 특화. 양·한방 통합 면역 치료 운영"
    },
    {
        "id":  "36",
        "district":  "동구",
        "name":  "아미유한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/암재활 한방병원",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활",
        "conditions":  "여성 암 중점 재활, 통합면역 치료, 도수치료, 고주파 온열 치료",
        "specialty":  "여성 암 재활 / 양·한방 협진",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 동구 방어진순환도로 851, 1,4,5층 (전하동)",
        "phone":  "052-700-8686",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "여성 암 환자 통합 면역 치료 및 암 재활 프로그램 특화"
    },
    {
        "id":  "37",
        "district":  "북구",
        "name":  "의료법인 기쁨의료재단 엠디한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/척추·관절 한방병원",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활",
        "conditions":  "추나요법, 근골격계 통증 치료, 교통사고 후유증, 척추·관절 재활",
        "specialty":  "한방재활의학과 / 주말진료",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 북구 호계로 332-1, 현대하이플러스 2,4층 (신천동)",
        "phone":  "052-286-3355",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "추나요법 및 교통사고 입원 재활 치료. 토·일요일 주말 진료 운영"
    },
    {
        "id":  "38",
        "district":  "남구",
        "name":  "자연뜰한방병원",
        "type":  "한방병원",
        "inclusion":  "한방재활/교통사고·통증 한방병원",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "외래/입원 한방재활",
        "conditions":  "교통사고 입원 재활, 통증 추나, 도수치료, 체형 교정, 소아 성장",
        "specialty":  "교통사고 재활 / 통증 추나",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 수암로 138, 9-11층 (야음동)",
        "phone":  "052-933-1075",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "교통사고 입원 치료 및 통증 추나/도수치료 특화. 소아 성장 프로그램 병행"
    },
    {
        "id":  "39",
        "district":  "남구",
        "name":  "남울산 한의원",
        "type":  "한의원",
        "inclusion":  "한방재활의학과 진료 한의원",
        "rehabDept":  "있음/확인필요",
        "specialists":  "확인필요",
        "careType":  "외래 한방재활",
        "conditions":  "척추·관절 질환, 통증 치료, 추나요법, 교통사고 후유증",
        "specialty":  "한방재활의학과 진료",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 문수로 368, 3층 (옥동)",
        "phone":  "052-917-1010",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "한방재활의학과를 진료 과목으로 운영 중"
    },
    {
        "id":  "40",
        "district":  "남구",
        "name":  "미올한의원",
        "type":  "한의원",
        "inclusion":  "한방재활의학과 전문의 보유 한의원",
        "rehabDept":  "있음",
        "specialists":  "한방재활의학과 전문의 1명(임경태 원장)",
        "careType":  "외래 한방재활",
        "conditions":  "안면마비, 턱관절, 체형 교정, 교통사고 후유증, 다이어트, 통증 치료",
        "specialty":  "한방재활의학과 전문의 진료",
        "recovery":  "해당없음",
        "workersComp":  "확인필요",
        "autoInsurance":  "확인필요",
        "dayRehab":  "확인필요",
        "address":  "울산광역시 남구 삼산로 283, 8층 (삼산동, 소망빌딩)",
        "phone":  "052-275-1075",
        "sources":  "대한한의사협회 한의원 검색 (www.akom.org)",
        "verification":  "AKOM 확인",
        "notes":  "한방재활의학과 전문의(임경태 원장) 진료 확인 (대한한의사전문의협회 등)"
    }
];
